version: 38
imports:
- projectPath: Templates
  revision: 0.0.6
jobs:
- name: Maven CI
  steps:
  - !UseTemplateStep
    name: maven build & deploy
    templateName: Tigase Server - Maven build & deploy
    paramMatrix:
    - name: timestamp-to-make-distinct
      valuesProvider: !ScriptingValues
        scriptName: get-timestamp
      secret: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
  postBuildActions:
  - !SendNotificationAction
    condition: failed
    receivers: group(TigaseCoreTeam)
