= HTTP API component
:author: Andrzej Wójcik
:date: 2016-08-21 13:28

Tigase HTTP API component is a generic container used to provide other HTTP related features as modules.
It is configured by default to run under name of `http`. Installations of Tigase XMPP Server run this component enabled by default under the same name even if not configured.

== Common module configuration
=== Enabling/disabling module
Every module can be activated or disabled by adjusting it's activity in following way:

[source,DSL]
----
http {
    %module_id% (active: false) {}
}
----

[NOTE]
You need to replace `%module_id%` with the id of module which you want to change activity (in this case, it will disable module).

=== Example
To disable REST module we would following entries can be used:

[source,DSL]
----
http {
    rest (active: false) {}
}
----

=== Context path
This property allows you to change the context path that is used by module. In other words, it allows you to change the prefix used by module.
By default every module (with exception of the Index module) uses a context path that is the same as module id. For example, the REST module ID results in the context path `/rest`

==== Example
Changing context path for REST module to `/api`

[source,dsl]
----
http {
    rest {
        context-path = '/api'
    }
}
----

=== List of virtual hosts
This provies the ability to limit modules to be available only on listed virtual hosts, and allows to set context path to `/` for more than one module.
Property accepts list of strings, which in the case of init.properties file format is list of comma separated domain names and in DSL it is written as list of strings (see xref:complexExample[Complex Example]).

==== Example
Here we want to move the REST module to be available only for requests directed to `api.example.com`

[source,dsl]
----
http {
    rest {
        vhosts = [ 'api.example.com' ]
    }
}
----

[[complexExample]]
=== Complex example
In this example we will disable the Index module and move REST module to `http://api.example.com/` and `http://rest.example.com`.

[source,dsl]
----
http {
    index (active: false) {}
    rest {
        context-path = '/'
        vhosts = [ 'api.example.com', 'rest.example.com' ]
    }
}
----

include::HTTP_API_Component_modules.asciidoc[]
